<?php
return [
    'customers' => [
        'index' => [
            'id',
            'name',
            'description',
        ],
        'detail' => [
            'name',
            'name_kana',
            'gender',
            'uuid',
            'status',
            'email',
            'phone_number',
            'zipcode',
            'address',
        ],
    ],
    'salons' => [
        'index' => [
            'id',
            'name',
            'description',
        ],
        'detail' => [
            'id',
            'name',
            'description',
            'zipcode',
            'address',
            'phone_number',
            'start_time',
            'closing_time',
            'holiday',
            'payment_methods',
        ],
    ],
    'stylists' => [
        'index' => [
            'id',
            'name',
            'salon_name',
        ],
        'detail' => [
            'id',
            'salon_id',
            'salon_name',
            'name',
            'name_kana',
            'gender',
            'appoint_fee',
            'stylist_history',
            'skill',
        ],
    ],
    'menus' => [
        'index' => [
            'id',
            'name',
            'salon_name',
        ],
        'detail' => [
            'id',
            'salon_id',
            'name',
            'description',
            'operation_time',
            'deadline time',
            'amount',
            'is_coupon',
            'conditions',
        ],
    ],
    'reservations' => [
        'index' => [
            'id',
            'customer_id',
            'customer_name',
            'menu_id',
            'menu_name',
            'salon_id',
            'salon_name',
            'total_amount',
        ],
        'detail' => [
            'id',
            'customer_id',
            'customer_name',
            'menu_id',
            'menu_name',
            'stylist_id',
            'stylist_name',
            'salon_id',
            'salon_name',
            'is_first',
            'total_amount',
            'visit_at',
            'created_at',
            'updated_at',
            'deleted_at',
        ],
    ],
];